services:
  db:
    image: bitnami/postgresql:11.14.0-debian-10-r28
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
     - postgres-data:/bitnami/postgresql
     - ./db-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
   postgres-data:
     driver: local

