name: Backend CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: ghcr.io/prop-house/prop-house-backend:${{ github.sha }}
      - name: Image digest
        run: "echo TAG: ghcr.io/prop-house/prop-house-backend:${{ github.sha }} SHA: ${{ steps.docker_build.outputs.digest }}"
